steps:
  # Step 1: Build Docker image from frontend directory
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-t', 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA',
        '-f', 'frontend/Dockerfile',
        'frontend'
      ]

  # Step 2: Push image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      ['push', 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA']

  # Step 3: Replace placeholder with actual image name in deployment YAML
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: bash
    args:
      - -c
      - |
        cd frontend
        sed "s|IMAGE_PLACEHOLDER|gcr.io/$PROJECT_ID/frontend:$SHORT_SHA|g" frontend-deployment.yaml > k8s-frontend-deployment.yaml

  # Step 4: Apply the deployment to the Kubernetes cluster
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend/k8s-frontend-deployment.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=lugx-cluster'

  # Step 5: Apply the service definition
  - name: 'gcr.io/cloud-builders/kubectl'
    args: ['apply', '-f', 'frontend/frontend-service.yaml']
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-c'
      - 'CLOUDSDK_CONTAINER_CLUSTER=lugx-cluster'

images:
  - 'gcr.io/$PROJECT_ID/frontend:$SHORT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'cloudbuild-deployer@lugx-gaming-project.iam.gserviceaccount.com'
