apiVersion: v1
kind: Service
metadata:
  name: game-service
spec:
  type: ClusterIP  # Internal-only access
  selector:
    app: game-service
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000