apiVersion: v1
kind: Service
metadata:
  name: analytics-service
  labels:
    app: analytics-service
spec:
  type: NodePort
  selector:
    app: analytics-service
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4000
      nodePort: 30080
  sessionAffinity: ClientIP  # Helps with session consistency