apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      initContainers:
      - name: init-chown
        image: busybox:1.35
        command: ["sh", "-c", "chown -R 101:101 /var/lib/clickhouse"]
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:25.6.2.5-alpine
        env:
        - name: CLICKHOUSE_HTTP_DEFAULT_USER  # Disables HTTP auth
          value: ""
        - name: CLICKHOUSE_HTTP_DEFAULT_PASSWORD
          value: ""
        - name: CLICKHOUSE_DB
          value: "analytics"
        ports:
        - containerPort: 8125
        - containerPort: 9000
        readinessProbe:
          exec:
            command:
            - clickhouse-client
            - --query
            - "SELECT 1"
          initialDelaySeconds: 10
          periodSeconds: 5
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
      volumes:
      - name: clickhouse-data
        persistentVolumeClaim:
          claimName: clickhouse-pvc

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  custom.xml: |
    <yandex>
      <profiles>
        <default>
          <max_memory_usage>10000000000</max_memory_usage>
        </default>
      </profiles>
      <users>
        <default>
          <networks>
            <ip>::/0</ip>  # Allow all IPs
          </networks>
          <profile>default</profile>
          <quota>default</quota>
        </default>
      </users>
    </yandex>

---

apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  type: ClusterIP  # Restrict to cluster-internal access
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8125
      targetPort: 8125
    - name: native
      port: 9000
      targetPort: 9000