apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse
  labels:
    app: clickhouse
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      initContainers:
      - name: init-chown
        image: busybox:1.35
        command: ["sh", "-c", "chown -R 101:101 /var/lib/clickhouse"]
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
      containers:
      - name: clickhouse
        image: clickhouse/clickhouse-server:23.3-alpine
        env:
        - name: CLICKHOUSE_DB
          value: "analytics"
        - name: CLICKHOUSE_USER
          value: "default"
        - name: CLICKHOUSE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: clickhouse-secrets
              key: password
        ports:
        - containerPort: 8123
          name: http
        - containerPort: 9000
          name: native
        volumeMounts:
        - name: clickhouse-data
          mountPath: /var/lib/clickhouse
        - name: clickhouse-config
          mountPath: /etc/clickhouse-server/config.d/custom.xml
          subPath: custom.xml
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        readinessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          tcpSocket:
            port: 9000
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: clickhouse-data
        persistentVolumeClaim:
          claimName: clickhouse-pvc
      - name: clickhouse-config
        configMap:
          name: clickhouse-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-config
data:
  custom.xml: |
    <yandex>
      <profiles>
        <default>
          <max_memory_usage>8000000000</max_memory_usage>
          <max_query_size>1073741824</max_query_size>
        </default>
      </profiles>
      <users>
        <default>
          <password_sha256_hex>$(echo -n "password" | sha256sum | cut -d' ' -f1)</password_sha256_hex>
          <networks>
            <ip>::/0</ip>
          </networks>
          <profile>default</profile>
          <quota>default</quota>
        </default>
      </users>
    </yandex>
---
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000