apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8125
      targetPort: 8125
    - name: native
      port: 9000
      targetPort: 9000